### PR TITLE
Reviews production bug

### PR DESCRIPTION
**Pull request by pauledwardmitchell**
Check this one out closely.  This might not be the best way to do this!!!

### CODE REVIEW

**Comment by laurieskelly** [comment]
@pauledwardmitchell can you give me a one-liner on what bug this is fixing so I can review it faster?

**Comment by pauledwardmitchell** [comment]
@laurieskelly - '/reviews' is a broken link on production... I think it is because it is trying to iterate through @reviews that are not there... I put in a conditional for <% if @reviews... %> to try to fix it

**Comment by pauledwardmitchell** [comment]
hard to fix w the seeds i have locally because i have a bunch of reviews for each category

**Comment by laurieskelly** [comment]
curious why that would break on production and not local. wonder if production has the latest?

**Comment by laurieskelly** [comment]
checked out this branch on production and it does not resolve the bug. here's a cap of the error from `log/production.log`

image

**Comment by pauledwardmitchell** [comment]
blast

**Comment by pauledwardmitchell** [comment]
oh!  look at line 24!  Is there a user associated with the review?  it is breaking on .full_name which is a method on User... not on reviews @laurieskelly

**Comment by laurieskelly** [comment]
Ah. I think this is again the difference between ratings and reviews. 

Some really smart person should have suggested making these separate in the database

**Comment by laurieskelly** [comment]
fixededed

image

**Pull request merged**
