### PR TITLE
Vendor views

### PR DESCRIPTION
**Pull request by pauledwardmitchell**
There are still things wrong with vendors show

screen shot 2016-10-22 at 4 09 26 pm

1) "Recent reviews" moves right.  I do not know why
2) The blue background could have more padding at the bottom

### CODE REVIEW

**Comment by pauledwardmitchell** [comment]
The issue is here:

#vendor-information{
  float: left;
  height: 100%;
  width: 45%;
  margin-right: 50px;
    h3{
    margin-bottom: 10px;
    }
}

#page-top{
  background-color: $blue-light;
  border-bottom: solid;
  border-color: #D3D3D3;
  padding: 10px;
  height: 100%;
  h1{
  display: inline-block;
  }
}

I just do not know how to tell it to make #page-top to take up as much room as #vendor-information

**Comment by pauledwardmitchell** [comment]
JK I THINK I FIXED IT

**Comment by laurieskelly** [comment]
this placement is confusing, should stars go somewhere else?

image

**Comment by laurieskelly** [comment]
oh i get it.  a star rating without a review shouldn't go in "recent reviews"

image

**Comment by pauledwardmitchell** [comment]
I've changed a lot of how this looks - see later PRs @laurieskelly

**Comment by laurieskelly** [comment]
ok cool @pauledwardmitchell. since it fixes some things and doesn't break other things I'll refrain from editorializing and approve. I think if I try to see the whole picture before merging any PRs this will never go anywhere

**Pull request merged**
